import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import React, { useState } from "react";

export default function Home() {
  const [cardHolderName, setCardHolderName] = useState("Jane Appleseed");
  const [cardNumber, setCardNumber] = useState<string>("0000 0000 0000 0000");
  const [MM, setMM] = useState("00");
  const [YY, setYY] = useState("00");
  const [cvc, setCvc] = useState("000");

  const handleCardHolderNameChange = (
    e: React.ChangeEvent<HTMLInputElement>
  ) => {
    if (e.target.value == "") {
      setCardHolderName("Jane Appleseed");
    } else {
      setCardHolderName(
        e.target.value.length > 24
          ? e.target.value.slice(0, 25) + "..."
          : e.target.value
      );
    }
  };

  const handleCardNumberChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    let value: undefined | string = e.target.value;
    value = value.replace(/\s/g, "");
    value = value.match(/.{1,4}/g)?.join(" ");
    if (typeof value === "undefined") {
      setCardNumber("0000 0000 0000 0000");
    } else {
      setCardNumber(value);
      e.target.value = value;
    }
  };

  const handleMMChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.value == "") {
      setMM("00");
    } else {
      let value: undefined | string = e.target.value;
      value = value.replace(/[^0-9]/g, "");
      setMM(value);
    }
  };

  const handleYYChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.value == "") {
      setYY("00");
    } else {
      let value: undefined | string = e.target.value;
      value = value.replace(/[^0-9]/g, "");
      setYY(value);
    }
  };

  const handleCvcChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.value == "") {
      setCvc("000");
    } else {
      let value: undefined | string = e.target.value;
      value = value.replace(/[^0-9]/g, "");
      setCvc(value);
    }
  };

  return (
    <>
      <Head>
        <title>Frontend Mentor | Interactive card details form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <div className={styles.cardPreview}>
            <div className={styles.cardFront}>
              <div className={styles.wrapper}>
                <Image
                  src={"/card-logo.svg"}
                  alt={"card logo"}
                  width={65}
                  height={35}
                />
                <span>{cardNumber}</span>
                <div>
                  <p>{cardHolderName}</p>
                  <p>
                    {MM}/{YY}
                  </p>
                </div>
              </div>
            </div>
            <div className={styles.cardBack}>
              <span>{cvc}</span>
            </div>
          </div>
          <div className={styles.debitCardForm}>
            <form>
              <label>CARDHOLDER NAME</label>
              <input
                type="text"
                placeholder="e.g. Jane Appleseed"
                onChange={handleCardHolderNameChange}
                maxLength={255}
              />
              <label>CARD NUMBER</label>
              <input
                type="text"
                placeholder="e.g. 1234 5678 9123 0000"
                onChange={handleCardNumberChange}
                maxLength={19}
              />
              <label>EXP. DATE (MM/YY)</label>
              <label>cvc</label>
              <input
                type="text"
                placeholder="MM"
                onChange={handleMMChange}
                maxLength={2}
              />
              <input
                type="text"
                placeholder="YY"
                onChange={handleYYChange}
                maxLength={2}
              />
              <input
                type="text"
                placeholder="e.g. 123"
                onChange={handleCvcChange}
                maxLength={3}
              />
              <input type="submit" value="Confirm" />
            </form>
          </div>
        </div>
      </main>
    </>
  );
}
